language: go

go:
  - 1.8.x

branches:
  only:
    - master

install:
  - curl -L https://github.com/google/protobuf/releases/download/v3.3.0/protoc-3.3.0-linux-x86_64.zip -o /tmp/protoc.zip
  - unzip /tmp/protoc.zip -d $HOME/protoc

env:
  - PATH=$HOME/protoc/bin:$PATH

script:
  - make
  - "[[ -z $(git status -s) ]]" # check if uncommited changes exist
