// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service.proto

/*
Package dns is a generated protocol buffer package.

It is generated from these files:
	proto/service.proto

It has these top-level messages:
	Host
	HostList
*/
package dns

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Host struct {
	Hostname string `protobuf:"bytes,1,opt,name=hostname" json:"hostname,omitempty"`
	Ip       string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
}

func (m *Host) Reset()                    { *m = Host{} }
func (m *Host) String() string            { return proto.CompactTextString(m) }
func (*Host) ProtoMessage()               {}
func (*Host) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Host) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Host) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type HostList struct {
	Hosts []*Host `protobuf:"bytes,1,rep,name=hosts" json:"hosts,omitempty"`
}

func (m *HostList) Reset()                    { *m = HostList{} }
func (m *HostList) String() string            { return proto.CompactTextString(m) }
func (*HostList) ProtoMessage()               {}
func (*HostList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HostList) GetHosts() []*Host {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func init() {
	proto.RegisterType((*Host)(nil), "dns.Host")
	proto.RegisterType((*HostList)(nil), "dns.HostList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DnsService service

type DnsServiceClient interface {
	Add(ctx context.Context, in *Host, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	Remove(ctx context.Context, in *Host, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	Get(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*HostList, error)
}

type dnsServiceClient struct {
	cc *grpc.ClientConn
}

func NewDnsServiceClient(cc *grpc.ClientConn) DnsServiceClient {
	return &dnsServiceClient{cc}
}

func (c *dnsServiceClient) Add(ctx context.Context, in *Host, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/dns.DnsService/Add", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dnsServiceClient) Remove(ctx context.Context, in *Host, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/dns.DnsService/Remove", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dnsServiceClient) Get(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*HostList, error) {
	out := new(HostList)
	err := grpc.Invoke(ctx, "/dns.DnsService/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DnsService service

type DnsServiceServer interface {
	Add(context.Context, *Host) (*google_protobuf.Empty, error)
	Remove(context.Context, *Host) (*google_protobuf.Empty, error)
	Get(context.Context, *google_protobuf.Empty) (*HostList, error)
}

func RegisterDnsServiceServer(s *grpc.Server, srv DnsServiceServer) {
	s.RegisterService(&_DnsService_serviceDesc, srv)
}

func _DnsService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Host)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DnsServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dns.DnsService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DnsServiceServer).Add(ctx, req.(*Host))
	}
	return interceptor(ctx, in, info, handler)
}

func _DnsService_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Host)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DnsServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dns.DnsService/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DnsServiceServer).Remove(ctx, req.(*Host))
	}
	return interceptor(ctx, in, info, handler)
}

func _DnsService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DnsServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dns.DnsService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DnsServiceServer).Get(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _DnsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dns.DnsService",
	HandlerType: (*DnsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _DnsService_Add_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _DnsService_Remove_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _DnsService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}

func init() { proto.RegisterFile("proto/service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x03, 0xf3, 0x84, 0x98, 0x53, 0xf2,
	0x8a, 0xa5, 0xa4, 0xd3, 0xf3, 0xf3, 0xd3, 0x73, 0x52, 0xf5, 0xc1, 0x42, 0x49, 0xa5, 0x69, 0xfa,
	0xa9, 0xb9, 0x05, 0x25, 0x95, 0x10, 0x15, 0x4a, 0x46, 0x5c, 0x2c, 0x1e, 0xf9, 0xc5, 0x25, 0x42,
	0x52, 0x5c, 0x1c, 0x19, 0xf9, 0xc5, 0x25, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0x9c, 0x41, 0x70, 0xbe, 0x10, 0x1f, 0x17, 0x53, 0x66, 0x81, 0x04, 0x13, 0x58, 0x94, 0x29, 0xb3,
	0x40, 0x49, 0x9b, 0x8b, 0x03, 0xa4, 0xc7, 0x27, 0xb3, 0xb8, 0x44, 0x48, 0x9e, 0x8b, 0x15, 0xa4,
	0xae, 0x58, 0x82, 0x51, 0x81, 0x59, 0x83, 0xdb, 0x88, 0x53, 0x2f, 0x25, 0xaf, 0x58, 0x0f, 0x24,
	0x1b, 0x04, 0x11, 0x37, 0x9a, 0xce, 0xc8, 0xc5, 0xe5, 0x92, 0x57, 0x1c, 0x0c, 0x71, 0x97, 0x90,
	0x16, 0x17, 0xb3, 0x63, 0x4a, 0x8a, 0x10, 0x42, 0x9d, 0x94, 0x98, 0x1e, 0xc4, 0x7d, 0x7a, 0x30,
	0xf7, 0xe9, 0xb9, 0x82, 0xdc, 0xa7, 0xc4, 0x20, 0xa4, 0xcb, 0xc5, 0x16, 0x94, 0x9a, 0x9b, 0x5f,
	0x96, 0x4a, 0x9c, 0x72, 0x3d, 0x2e, 0x66, 0xf7, 0xd4, 0x12, 0x21, 0x1c, 0x0a, 0xa4, 0x78, 0xe1,
	0x66, 0x80, 0x1c, 0xae, 0xc4, 0x90, 0xc4, 0x06, 0x56, 0x60, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff,
	0x5d, 0xbe, 0x1d, 0x0d, 0x3a, 0x01, 0x00, 0x00,
}
